name: lantern
description: Lantern
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  wechat_assets_picker:
    git: https://github.com/getlantern/wechat_assets_picker.git
  audioplayers: ^0.18.3
  
  auto_route: ^2.2.0
  back_button_interceptor: ^5.0.0
  badges: ^2.0.0-nullsafety.1
  bot_toast: ^4.0.1
  dotted_border: ^2.0.0
  email_validator: ^2.0.1
  emoji_picker_flutter: ^1.0.6
  extended_image: ^4.1.0
  flag: ^5.0.0-nullsafety
  flutter_svg: ^0.21.0-nullsafety.0
  flutter_switch: ^0.3.0
  fluttertoast: 8.0.6
  focused_menu: ^1.0.5
  google_fonts: null
  i18n_extension: ^4.0.0
  loader_overlay: ^2.0.0
  pedantic: ^1.11.0
  photo_manager: ^1.2.1
  pin_code_text_field: ^1.8.0
  protobuf: any
  provider: ^5.0.0
  qr_code_scanner: ^0.4.0
  qr_flutter: ^4.0.0
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  share: ^2.0.1
  stop_watch_timer: ^1.0.0
  styled_text: ^3.0.1
  url_launcher: ^6.0.3
  uuid: ^3.0.3
  video_player: ^2.1.5
  wechat_camera_picker: ^2.1.0
  sizer: ^2.0.13
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^2.1.0
  build_runner: ^2.0.5

  test: ^1.15.7

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/disappear/
    - assets/locales/
