name: android

on:
  push:
    branches: [ main ]

permissions:
  contents: read

env:
  GOPRIVATE: github.com/getlantern
jobs:
  build:
    runs-on: ubuntu-latest-8-cores
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: Pull LFS objects
      run: git lfs pull

    # Install Flutter
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.7.12"
        channel: "stable"
    - run: flutter --version

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Granting private modules access
      run: |
        git config --global url."https://${{ secrets.GH_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

    - name: Build Lantern core Android library
      run: make android-lib

    - name: Setup Sentry CLI
      uses: mathieu-bour/setup-sentry-cli@v1
      with:
        version: latest
        token: ${{ SECRETS.SENTRY_TOKEN }} # from GitHub secrets
        organization: getlantern
        project: android

    - name: Setup JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11

    - name: Setup protoc
      uses: arduino/setup-protoc@v1.1.2

    - name: Install Flutter dependencies
      run: |
        flutter pub get
        dart pub global activate protoc_plugin

    - name: Set gradle properties
      env:
        GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
      run: |
        mkdir -p ~/.gradle/
        echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
        echo "${GRADLE_PROPERTIES}" > ~/.gradle/gradle.properties

    - name: Decode Keystore
      id: write_file
      uses: timheuer/base64-to-file@v1.2
      with:
        fileName: 'keystore.release.jks'
        fileDir: './android/app'
        encodedString: ${{ secrets.KEYSTORE }}

    - name: Build with Gradle
      run: make android-release ANDROID_ARCH=all

    - name: Build Mobile Bundle
      run: make android-bundle ANDROID_ARCH=all
