name: Build Darwin
on:
  workflow_call:
    inputs:
      version_file:
        type: string
        required: true
      version:
        type: string
        required: true
      prefix:
        type: string
        required: true

env:
  GOPRIVATE: github.com/getlantern
  S3_BUCKET: lantern
jobs:
  build-darwin:
    permissions:
      contents: "read"
      id-token: "write"
    env:
      version: ${{ inputs.version }}
      version_file: ${{ inputs.version_file }}
      prefix: ${{ inputs.prefix }}
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: Pull LFS objects
      run: git lfs pull

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 14.3.1

    - name: Granting private modules access
      run: |
        git config --global url."https://${{ secrets.GH_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

    - name: Repo access
      run: |
        mkdir /tmp/cache
        echo "machine github.com login ${{ secrets.GH_TOKEN }} password x-oauth-basic" > /tmp/cache/.netrc
        chmod 600 /tmp/cache/.netrc

    - name: Setup Sentry CLI
      uses: mathieu-bour/setup-sentry-cli@v1
      with:
        version: latest
        token: ${{ SECRETS.SENTRY_TOKEN }} # from GitHub secrets
        organization: getlantern
        project: android

    - name: Build liblantern.dylib
      run: go build -buildmode=c-shared -o desktop/liblantern.dylib desktop/lib.go

    - uses: actions/upload-artifact@v3
      with:
        name: libgo-mac-build
        if-no-files-found: error
        path: |
          desktop/liblantern.dylib

      # Install Flutter
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.9'
        channel: "stable"

    - run: flutter --version

    - name: Setup protoc
      uses: arduino/setup-protoc@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Activate protoc-gen-dart plugin
      run: |
        dart pub global activate protoc_plugin

    - name: Build Flutter app
      run: flutter build macos

