name: Push binaries

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
      prefix:
        type: string
        required: true
      version_file:
        type: string
        required: true

permissions:
  contents: read

env:
  GOPRIVATE: github.com/getlantern
  S3_BUCKET: lantern
jobs:
    push-binaries:
      runs-on:
        group: large-runners
      env:
        version: ${{ inputs.version }}
        prefix: ${{ inputs.prefix }}
      steps:
        - name: Setup S3cmd cli tool
          uses: s3-actions/s3cmd@v1.4.0
          with:
            provider: aws
            region: ${{ secrets.AWS_REGION }}
            access_key: ${{ secrets.AWS_ACCESS_KEY }}
            secret_key: ${{ secrets.AWS_SECRET_KEY }}

        - name: Push binaries to s3
          env:
            VERSION: "${{ env.version }}"
            APK: "${{ env.prefix }}-${{ env.version }}.apk"
            AAB: "${{ env.prefix }}-${{ env.version }}.aab"
          run: |
            mv lantern-installer.apk "$APK"
            mv lantern-installer.aab "$AAB"
            cp "$APK" ${{ env.prefix }}.apk
            cp "$AAB" ${{ env.prefix }}.aab
            echo ${{ env.version }} > ${{ env.version_file }}
            shasum -a 256 "$APK" | cut -d " " -f 1 > "$APK".sha256
            shasum -a 256 "$AAB" | cut -d " " -f 1 > "$AAB".sha256
            cp "$APK".sha256 ${{ env.prefix }}.apk.sha256
            cp "$AAB".sha256 ${{ env.prefix }}.aab.sha256
            s3cmd put --acl-public "$APK" ${{ env.version_file }} "$APK".sha256 ${{ env.prefix }}.apk.sha256 ${{ env.prefix }}.apk "s3://$S3_BUCKET"
            s3cmd put --acl-public "$AAB" "$AAB".sha256 ${{ env.prefix }}.aab.sha256 ${{ env.prefix }}.aab "s3://$S3_BUCKET"
            s3cmd modify --add-header='content-type':'application/vnd.android.package-archive' "s3://$S3_BUCKET/$APK"
            s3cmd modify --add-header='content-type':'application/vnd.android.package-archive' "s3://$S3_BUCKET/${{ env.prefix }}.apk"
            s3cmd modify --add-header='content-type':'application/vnd.android.package-archive' "s3://$S3_BUCKET/$AAB"
            s3cmd modify --add-header='content-type':'application/vnd.android.package-archive' "s3://$S3_BUCKET/${{ env.prefix }}.aab"

        - name: Download the apk build output
          uses: actions/download-artifact@v3
          with:
            name: android-apk-build
        - name: Download the aab build output
          uses: actions/download-artifact@v3
          with:
            name: android-aab-build
        - name: Upload Android App bundle to Play Store (beta)
          if: inputs.prefix == 'lantern-installer-preview'
          uses: r0adkll/upload-google-play@v1
          with:
           serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
           packageName: org.getlantern.lantern
           releaseFiles: lantern-installer.aab
           track: beta
        - name: Upload Android App bundle to Play Store (production)
          if: inputs.prefix == 'lantern-installer'
          uses: r0adkll/upload-google-play@v1
          with:
           serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
           packageName: org.getlantern.lantern
           releaseFiles: lantern-installer.aab
           track: production
        - name: Grant private modules access
          run: git config --global url."https://${{ secrets.GH_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
        - name: Clone binaries repo
          run: git clone --depth 1 https://github.com/getlantern/lantern-binaries
        - name: Rename builds
          run: |
            diff lantern-installer.apk ${{ env.prefix }}.apk || mv -f lantern-installer.apk ${{ env.prefix }}.apk
            diff lantern-installer.aab ${{ env.prefix }}.aab || mv -f lantern-installer.aab ${{ env.prefix }}.aab
        - name: Prepare sha256 sums
          run: |
            shasum -a 256 ${{ env.prefix }}.apk | cut -d " " -f 1 > ${{ env.prefix }}.apk.sha256
            shasum -a 256 ${{ env.prefix }}.aab | cut -d " " -f 1 > ${{ env.prefix }}.aab.sha256
        - name: Commit
          run: |
            mv lantern-installer* ./lantern-binaries/
            cd lantern-binaries
            git config user.email "admin@getlantern.org"
            git config user.name "Lantern Bot"
            git add .
            git commit -m "Lantern binaries for version ${{ env.version }}"
            git push origin main
