name: release

on:
  push:
    branches: [ atavism/google-pay-test-purchase ]

permissions:
  contents: read

env:
  GOPRIVATE: github.com/getlantern
  S3_BUCKET: lantern
jobs:
    set-version:
      runs-on:
        group: large-runners
      outputs:
        version: ${{ steps.set-version.outputs.version }}
        prefix: ${{ steps.set-version.outputs.prefix }}
        version_file: ${{ steps.set-version.outputs.version_file }}
      steps:
      - id: set-version
        shell: python
        run: |
          import sys, os
          ref = os.environ.get("GITHUB_REF","")
          if "refs/tags/lantern" not in ref:
            li = 'lantern-installer-dev'
            vf = 'version-android-dev.txt'
            version = '9999.99.99-dev'
          else:
            a = ref.strip().replace('refs/tags/lantern-', '')
            parts = a.split('-',1)
            suffix = parts[1] if len(parts)>1 else ''
            beta = 'beta' in suffix
            internal = 'internal' in suffix
            if beta:
                li = 'lantern-installer-preview'
                vf = 'version-android-beta.txt'
                version = parts[0]
            elif internal:
                li = 'lantern-installer-internal'
                vf = 'version-android-internal.txt'
                version = parts[0]
            else:
                li = 'lantern-installer'
                vf = 'version-android.txt'
                version = a
          print('Setting version to ' + version)
          print('Setting prefix to ' + li)
          print('Setting version file to ' + vf)
          print(f'::set-output name=version::{version}')
          print(f'::set-output name=prefix::{li}')
          print(f'::set-output name=version_file::{vf}')
    build-android:
      needs: set-version
      env:
        version: ${{ needs.set-version.outputs.version }}
        version_file: ${{ needs.set-version.outputs.version_file }}
        prefix: ${{ needs.set-version.outputs.prefix }}
      runs-on:
        group: large-runners
      steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - name: Pull LFS objects
        run: git lfs pull

      # Install Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.5"
          channel: "stable"
      - run: flutter --version

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Granting private modules access
        run: |
          git config --global url."https://${{ secrets.GH_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Setup Sentry CLI
        uses: mathieu-bour/setup-sentry-cli@v1
        with:
          version: latest
          token: ${{ SECRETS.SENTRY_TOKEN }} # from GitHub secrets
          organization: getlantern
          project: android

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup protoc
        uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ secrets.GH_TOKEN }}

      - name: Activate protoc-gen-dart plugin
        run: |
          echo "${HOME}/.pub-cache/bin" >> $GITHUB_PATH
          dart pub global activate protoc_plugin
          mkdir -p "${HOME}/.pub-cache/bin"
          mv "${FLUTTER_ROOT}/.pub-cache/bin/protoc-gen-dart" "${HOME}/.pub-cache/bin"

      - name: Set gradle properties
        env:
          GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
        run: |
          mkdir -p ~/.gradle/
          echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
          echo "${GRADLE_PROPERTIES}" > ~/.gradle/gradle.properties

      - name: Decode Keystore
        id: write_file
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'keystore.release.jks'
          fileDir: './android/app'
          encodedString: ${{ secrets.KEYSTORE }}

      - name: Build Android installers
        run: make package-android
        env:
          INTERSTITIAL_AD_UNIT: "${{ secrets.INTERSTITIAL_AD_UNIT_ID }}"
          VERSION: "${{ env.version }}"

      - uses: actions/upload-artifact@v3
        with:
          name: android-apk-build
          retention-days: 2
          path: |
            lantern-installer.apk

      - uses: actions/upload-artifact@v3
        with:
          name: android-aab-build
          retention-days: 2
          path: |
            lantern-installer.aab

      - name: Install jq
        run: sudo apt-get install jq

    browserstack:
      uses: ./.github/workflows/browserstack.yml
      secrets: inherit
      needs: build-android
